### ISSUE TITLE
org.apache.http.NoHttpResponseException

### ISSUE THREAD

**Issue by lusoel** [denger/sendcloud4j#11]
我用您的sendcloud4j发送邮件是会偶现下面的错误，我们发邮件一般会连续发送。

       
org.apache.http.NoHttpResponseException: api.sendcloud.net:80 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.apache.http.client.fluent.Request.internalExecute(Request.java:173)
	at org.apache.http.client.fluent.Request.execute(Request.java:177)
	at io.jstack.sendcloud4j.mail.MailWebApi.requestSend(MailWebApi.java:64)
	at io.jstack.sendcloud4j.mail.MailWebApi.send(MailWebApi.java:38)
	at com.htdata.server.service.EmailSender.SendCloudEmailSender.sendEmail(SendCloudEmailSender.java:39)
	at com.htdata.util.EmailSendUtil.sendSms(EmailSendUtil.java:22)
	at com.htdata.thread.SendThread.sendMsg(SendThread.java:136)
	at com.htdata.thread.SendThread.run(SendThread.java:50)
	at java.lang.Thread.run(Unknown Source)

**Comment by denger** [comment]
建议增长超时时间试试？
