### ISSUE TITLE
调用 api 报错

### ISSUE THREAD

**Issue by freezhan** [denger/sendcloud4j#3]
你好　我按照 readme 中发送后报错信息如下,
请问哪里出错了呢　

```java
    public static void main(String[] args) {
        String apiUser = "XXX";
        String apiKey = "XXX";
        SendCloud webapi = SendCloud.createWebApi(apiUser, apiKey);

        Email email = Email.template("send_template").from("XXX@xxx").fromName(" test sendcloud4j").subject("title").to("xxx@xxx");
        
        Result result = webapi.mail().send(email);
        System.out.println(JSON.toJSONString(result));
    }

```

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.http.impl.conn.PoolingHttpClientConnectionManager.setValidateAfterInactivity(I)V
	at org.apache.http.client.fluent.Executor.<clinit>(Executor.java:99)
	at org.apache.http.client.fluent.Request.execute(Request.java:177)
	at io.jstack.sendcloud4j.mail.MailWebApi.requestSend(MailWebApi.java:64)
	at io.jstack.sendcloud4j.mail.MailWebApi.send(MailWebApi.java:38)
	at com.blueocn.dconsumer.workers.sendcloud.Main.main(Main.java:34)

```

**Comment by denger** [comment]
请看一下你用的 httpclient 的版本是什么? 看上去是因为你引用的 httpclinet jar 没有 PoolingHttpClientConnectionManager.setValidateAfterInactivity 方法导致。

**Comment by freezhan** [comment]
谢谢,代码中没有引用 httpclient

```java
Result result = webapi.mail().send(email);
```

这段代码不会自动 post 过去么

**Comment by denger** [comment]
必须要引用 httpclient  的, sendcloud4j 引用的 httpclient version 是4.5.1，具体可以看一下[pom.xml](https://github.com/denger/sendcloud4j/blob/master/pom.xml)。应该是你引用了其它 jar 中有依赖了 httpclient 其它版本导致。

没错，执行 send 即做 http post 操作。

**Comment by yaoliquan123123123** [comment]
没太看懂 能不能教教我 QQ302528116   求讲解
